export type JobKind = "image" | "video";
export type JobStatus = "queued" | "running" | "succeeded" | "failed";

export type GenerationJob = {
  id: string;
  kind: JobKind;
  provider: string;
  model: string;
  prompt: string;
  status: JobStatus;
  createdAt: number;
  completeAt: number;
  assets: Array<{
    id: string;
    type: JobKind;
    title: string;
    url?: string;
    preview: string;
  }>;
};

type JobStoreGlobal = typeof globalThis & {
  aiVideoCanvasJobs?: Map<string, GenerationJob>;
};

const globalStore = globalThis as JobStoreGlobal;

export const jobs = globalStore.aiVideoCanvasJobs ?? new Map<string, GenerationJob>();
globalStore.aiVideoCanvasJobs = jobs;

export function createJob(input: {
  kind: JobKind;
  provider: string;
  model: string;
  prompt: string;
  durationMs?: number;
}) {
  const now = Date.now();
  const id = `${input.kind}_${now}_${Math.random().toString(36).slice(2, 8)}`;
  const job: GenerationJob = {
    id,
    kind: input.kind,
    provider: input.provider,
    model: input.model,
    prompt: input.prompt,
    status: "queued",
    createdAt: now,
    completeAt: now + (input.durationMs ?? 2200),
    assets: []
  };

  jobs.set(id, job);
  return getJob(id);
}

export function getJob(id: string) {
  const job = jobs.get(id);

  if (!job) {
    return null;
  }

  const now = Date.now();
  const status: JobStatus =
    now >= job.completeAt ? "succeeded" : now - job.createdAt > 600 ? "running" : "queued";

  const assets =
    status === "succeeded" && job.assets.length === 0 ? makeAssets(job) : job.assets;

  const updated = {
    ...job,
    status,
    assets
  };

  jobs.set(id, updated);
  return updated;
}

function makeAssets(job: GenerationJob): GenerationJob["assets"] {
  if (job.kind === "image") {
    return [1, 2, 3].map((index) => ({
      id: `${job.id}_asset_${index}`,
      type: "image",
      title: `Image result ${index}`,
      preview: `Generated by ${job.provider}/${job.model}: ${job.prompt.slice(0, 64)}`
    }));
  }

  return [
    {
      id: `${job.id}_asset_1`,
      type: "video",
      title: "Video result 1",
      preview: `Generated by ${job.provider}/${job.model}: ${job.prompt.slice(0, 72)}`
    }
  ];
}
