import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { readStringByPath } from "@/lib/api/response-path";
import { getJob } from "@/lib/jobs/job-store";

type JsonRecord = Record<string, unknown>;

function makeUrl(baseUrl: string, path: string) {
  if (/^https?:\/\//i.test(path)) return path;
  return `${baseUrl.replace(/\/+$/, "")}/${path.replace(/^\/+/, "")}`;
}

function isRecord(value: unknown): value is JsonRecord {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function firstRecord(value: unknown) {
  return Array.isArray(value) && isRecord(value[0]) ? value[0] : undefined;
}

function stringValue(value: unknown) {
  return typeof value === "string" && value.trim() ? value.trim() : "";
}

function normalizeStatusText(statusText: string): "queued" | "running" | "succeeded" | "failed" {
  const normalized = statusText.toLowerCase();
  if (["succeeded", "success", "completed", "complete", "done", "finished"].includes(normalized)) {
    return "succeeded";
  }
  if (["failed", "error", "cancelled", "canceled", "timeout"].includes(normalized)) {
    return "failed";
  }
  if (["queued", "pending", "created", "waiting"].includes(normalized)) {
    return "queued";
  }
  return "running";
}

function readStatus(payload: unknown, configuredPath?: string | null): "queued" | "running" | "succeeded" | "failed" {
  const configured = readStringByPath(payload, configuredPath);
  if (configured) return normalizeStatusText(configured);

  if (!isRecord(payload)) return "running";
  const data = isRecord(payload.data) ? payload.data : firstRecord(payload.data);
  const result = isRecord(payload.result) ? payload.result : undefined;
  const statusText = (
    stringValue(payload.status) ||
    stringValue(payload.state) ||
    stringValue(payload.task_status) ||
    stringValue(data?.status) ||
    stringValue(data?.state) ||
    stringValue(result?.status) ||
    stringValue(result?.state)
  );

  return normalizeStatusText(statusText);
}

function readError(payload: unknown, configuredPath?: string | null) {
  const configured = readStringByPath(payload, configuredPath);
  if (configured) return configured;

  if (!isRecord(payload)) return "";
  const error = isRecord(payload.error) ? payload.error : undefined;
  return (
    stringValue(payload.message) ||
    stringValue(payload.error) ||
    stringValue(error?.message) ||
    stringValue(payload.detail)
  );
}

function readVideoUrl(payload: unknown, configuredPath?: string | null): string {
  const configured = readStringByPath(payload, configuredPath);
  if (configured) return configured;

  if (!isRecord(payload)) return "";

  const direct =
    stringValue(payload.url) ||
    stringValue(payload.video_url) ||
    stringValue(payload.videoUrl) ||
    stringValue(payload.output_url) ||
    stringValue(payload.outputUrl);
  if (direct) return direct;

  const data = firstRecord(payload.data) ?? (isRecord(payload.data) ? payload.data : undefined);
  const output = isRecord(payload.output) ? payload.output : undefined;
  const result = isRecord(payload.result) ? payload.result : undefined;
  const video = firstRecord(payload.videos);
  const asset = firstRecord(payload.assets);

  return (
    stringValue(data?.url) ||
    stringValue(data?.video_url) ||
    stringValue(data?.videoUrl) ||
    stringValue(output?.url) ||
    stringValue(output?.video_url) ||
    stringValue(output?.videoUrl) ||
    stringValue(result?.url) ||
    stringValue(result?.video_url) ||
    stringValue(result?.videoUrl) ||
    stringValue(video?.url) ||
    stringValue(video?.video_url) ||
    stringValue(asset?.url) ||
    stringValue(asset?.video_url)
  );
}

function parseAssetsJson(value: string) {
  try {
    const parsed = JSON.parse(value);
    if (Array.isArray(parsed)) return { assets: parsed, meta: undefined as JsonRecord | undefined };
    if (isRecord(parsed)) {
      return {
        assets: Array.isArray(parsed.assets) ? parsed.assets : [],
        meta: isRecord(parsed.meta) ? parsed.meta : undefined
      };
    }
  } catch {
    return { assets: [], meta: undefined };
  }
  return { assets: [], meta: undefined };
}

function videoAsset(input: {
  id: string;
  prompt: string;
  provider: string;
  model: string;
  videoUrl: string;
  imageUrl?: string;
  projectId?: string | null;
  raw?: unknown;
}) {
  return {
    id: `${input.id}_asset_1`,
    projectId: input.projectId ?? null,
    type: "video",
    title: `${input.prompt.slice(0, 36)}${input.prompt.length > 36 ? "..." : ""}`,
    preview: `Video generated by ${input.provider}/${input.model}`,
    url: input.videoUrl,
    videoUrl: input.videoUrl,
    prompt: input.prompt,
    imageUrl: input.imageUrl ?? "",
    provider: input.provider,
    model: input.model,
    raw: input.raw
  };
}

async function saveAssets(jobId: string, assets: Array<ReturnType<typeof videoAsset>>, projectId?: string | null) {
  for (const asset of assets) {
    await prisma.asset.upsert({
      where: { id: asset.id },
      create: {
        id: asset.id,
        projectId: projectId ?? null,
        type: "video",
        title: asset.title,
        preview: asset.preview,
        payloadJson: JSON.stringify(asset),
        sourceJobId: jobId
      },
      update: {
        projectId: projectId ?? null,
        type: "video",
        title: asset.title,
        preview: asset.preview,
        payloadJson: JSON.stringify(asset),
        sourceJobId: jobId
      }
    });
  }
}

async function localJobResponse(jobId: string) {
  const job = getJob(jobId);

  if (!job) {
    return null;
  }

  await prisma.generationJob.update({
    where: { id: job.id },
    data: {
      status: job.status,
      assetsJson: JSON.stringify(job.assets),
      completedAt: job.status === "succeeded" ? new Date() : null
    }
  });

  return job;
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ jobId: string }> }
) {
  const { jobId } = await params;
  const storedJob = await prisma.generationJob.findUnique({ where: { id: jobId } });

  if (!storedJob) {
    const localJob = await localJobResponse(jobId);
    return localJob
      ? NextResponse.json(localJob)
      : NextResponse.json({ error: "Job not found" }, { status: 404 });
  }

  const parsed = parseAssetsJson(storedJob.assetsJson);
  if (!parsed.meta?.external) {
    const localJob = await localJobResponse(jobId);
    if (localJob) return NextResponse.json(localJob);
    return NextResponse.json({
      id: storedJob.id,
      kind: "video",
      provider: storedJob.provider,
      model: storedJob.model,
      prompt: storedJob.prompt,
      status: storedJob.status,
      assets: parsed.assets
    });
  }

  const credentialId = stringValue(parsed.meta.credentialId);
  const externalJobId = stringValue(parsed.meta.externalJobId);
  const selected = await prisma.modelCredential.findUnique({ where: { id: credentialId } });

  if (!selected || !selected.baseUrl || !selected.enabled) {
    return NextResponse.json({
      id: storedJob.id,
      kind: "video",
      provider: storedJob.provider,
      model: storedJob.model,
      prompt: storedJob.prompt,
      status: "failed",
      assets: parsed.assets,
      error: "The video API configuration used by this job is missing or disabled."
    });
  }

  const rawStatusPath =
    stringValue(parsed.meta.statusUrl) ||
    selected.statusPath ||
    `/videos/generations/${encodeURIComponent(externalJobId)}`;
  const statusPath = rawStatusPath
    .replaceAll("{id}", encodeURIComponent(externalJobId))
    .replaceAll(":id", encodeURIComponent(externalJobId));
  let response: Response;
  try {
    response = await fetch(makeUrl(selected.baseUrl, statusPath), {
      headers: {
        Authorization: `Bearer ${selected.apiKey}`,
        "Content-Type": "application/json"
      }
    });
  } catch (error) {
    return NextResponse.json({
      id: storedJob.id,
      kind: "video",
      provider: storedJob.provider,
      model: storedJob.model,
      prompt: storedJob.prompt,
      status: "running",
      assets: parsed.assets,
      error: error instanceof Error ? error.message : String(error)
    });
  }

  if (!response.ok) {
    const detail = await response.text();
    await prisma.generationJob.update({
      where: { id: storedJob.id },
      data: { status: "failed" }
    });
    return NextResponse.json({
      id: storedJob.id,
      kind: "video",
      provider: storedJob.provider,
      model: storedJob.model,
      prompt: storedJob.prompt,
      status: "failed",
      assets: parsed.assets,
      error: detail.slice(0, 1200)
    });
  }

  const payload = await response.json().catch(() => ({}));
  const status = readStatus(payload, selected.responseStatusPath);
  const videoUrl = readVideoUrl(payload, selected.responseUrlPath);
  const prompt = stringValue(parsed.meta.prompt) || storedJob.prompt;
  const imageUrl = stringValue(parsed.meta.imageUrl);
  const assets =
    videoUrl && (status === "succeeded" || status === "running")
      ? [
          videoAsset({
            id: storedJob.id,
            prompt,
            provider: storedJob.provider,
            model: storedJob.model,
            videoUrl,
            imageUrl,
            projectId: storedJob.projectId,
            raw: payload
          })
        ]
      : parsed.assets;
  const nextStatus = videoUrl ? "succeeded" : status;

  await prisma.generationJob.update({
    where: { id: storedJob.id },
    data: {
      status: nextStatus,
      assetsJson: JSON.stringify({ meta: { ...parsed.meta, lastPayload: payload }, assets }),
      completedAt: nextStatus === "succeeded" ? new Date() : null
    }
  });

  if (nextStatus === "succeeded") {
    await saveAssets(storedJob.id, assets as Array<ReturnType<typeof videoAsset>>, storedJob.projectId);
  }

  return NextResponse.json({
    id: storedJob.id,
    kind: "video",
    provider: storedJob.provider,
    model: storedJob.model,
    prompt: storedJob.prompt,
    status: nextStatus,
    assets,
    error: nextStatus === "failed" ? readError(payload, selected.responseErrorPath) || "External video job failed." : undefined
  });
}
